name: ${project.name}
version: ${project.version}
main: net.azisaba.yukielevator.${project.name}
author: YukiLeafX

permissions:
  yukielevator.use:
    default: true
    children:
      yukielevator.up: true
      yukielevator.down: true
  yukielevator.up:
    default: true
  yukielevator.down:
    default: true
  yukielevator.command.yukielevator:
    default: op

commands:
  yukielevator:
    aliases: [ye]
    permission: yukielevator.command.yukielevator
